In [2]:
import numpy as np
import pandas as pd

In [5]:
np.ceil(100*np.log2(10))

333.0

In [15]:
t = "this is a string object"
t.capitalize()

'This is a string object'

In [16]:
t.upper()

'THIS IS A STRING OBJECT'

In [17]:
t.lower()

'this is a string object'

In [18]:
t.split()

['this', 'is', 'a', 'string', 'object']

In [21]:
t.find('string') #특정 단어가 처음으로 나타나는 위치를 반환

10

In [22]:
t.find('Python') #찾으려는 단어가 없으면 -1을 반환

-1

In [24]:
t.replace(' ', 'l') # 빈칸을 'ㅣ'로 치환

'thislislalstringlobject'

In [28]:
'http://www.python.org'.strip('htp:/')

'www.python.org'

### Regular Expression

In [29]:
import re

In [30]:
series ="""
'01/18/2014 13:00:00', 100, '1st';
'01/18/2014 13:30:00', 110, '2nd';
'01/18/2014 14:00:00', 120, '3rd';
"""

In [31]:
dt = re.compile("'[0-9/:\s]+'") #datetime

In [32]:
result = dt.findall(series)
result

["'01/18/2014 13:00:00'", "'01/18/2014 13:30:00'", "'01/18/2014 14:00:00'"]

In [34]:
from datetime import datetime
pydt = datetime.strptime(result[0].replace("'",""), '%m/%d/%Y %H:%M:%S')
pydt

datetime.datetime(2014, 1, 18, 13, 0)

### Tuple

In [35]:
t = (1, 2.5, 'data')
type(t)

tuple

In [37]:
t= 1, 2.5, 'data'
print(t)
print(type(t))

(1, 2.5, 'data')
<class 'tuple'>


In [41]:
type(t[0]) != type(t[2])

True

In [42]:
t.count('data')

1

In [45]:
print(t.index(1), t.index(2.5), t.index('data'))

0 1 2


### List

In [59]:
l = [1, 2.5, 'data']
l[2]

'data'

In [60]:
l = list(t)
l

[1, 2.5, 'data']

In [61]:
l.append([4.3])
l

[1, 2.5, 'data', [4.3]]

In [62]:
l.extend([1.0, 1.5, 2.0])
l

[1, 2.5, 'data', [4.3], 1.0, 1.5, 2.0]

In [63]:
l.insert(1, 'insert')
l

[1, 'insert', 2.5, 'data', [4.3], 1.0, 1.5, 2.0]

In [64]:
l.remove('data') # 가장 처음으로 나타나는 'data'원소를 제거.
l

[1, 'insert', 2.5, [4.3], 1.0, 1.5, 2.0]

In [65]:
p = l.pop(3) # 특정 인덱스 위치의 원소를 삭제하고 그 값을 반환
print(l,p)

[1, 'insert', 2.5, 1.0, 1.5, 2.0] [4.3]


In [66]:
l[2:5]

[2.5, 1.0, 1.5]

### 함수형 프로그래밍(filter, map, reduce)

In [67]:
def even(x):
    return x % 2 == 0
even(3)

False

In [81]:
for i in map(even, range(10)): # map(function, list)로 보는 게 맞음. list에다가 한번에 function을 취하고 싶을 때.
    print(i)

True
False
True
False
True
False
True
False
True
False


In [82]:
for i in map(lambda x: x**2, range(10)):
    print(i)

0
1
4
9
16
25
36
49
64
81


In [84]:
for i in filter(even, range(15)):
    print(i) # even의 반환값이 True 인 것만 

0
2
4
6
8
10
12
14


### Dictionary

In [88]:
d = {'Name' : 'Angela Merkel',
    'Country': 'Germany',
    'Profession': 'Chancelor',
    'Age': 60}
type(d)

dict

In [89]:
print(d['Name'], d['Age'])

Angela Merkel 60


In [90]:
d.keys()

dict_keys(['Name', 'Country', 'Profession', 'Age'])

In [91]:
d.values()

dict_values(['Angela Merkel', 'Germany', 'Chancelor', 60])

In [92]:
d.items()

dict_items([('Name', 'Angela Merkel'), ('Country', 'Germany'), ('Profession', 'Chancelor'), ('Age', 60)])

In [93]:
birthday = True
if birthday:
    d['Age'] += 1
print(d['Age'])

61


In [96]:
for key, value in d.items():
    print(key, value)

Name Angela Merkel
Country Germany
Profession Chancelor
Age 61


### Set

In [99]:
s = set(['u', 'd', 'du', 'ud', 'd', 'du'])
s

{'d', 'du', 'u', 'ud'}

In [101]:
t = set(['d', 'dd', 'uu', 'u'])
t

{'d', 'dd', 'u', 'uu'}

In [102]:
s.union(t) #합집합

{'d', 'dd', 'du', 'u', 'ud', 'uu'}

In [103]:
s.intersection(t) # 교집합

{'d', 'u'}

In [106]:
s.difference(t) # 차집합

{'du', 'ud'}

In [105]:
t.difference(s)

{'dd', 'uu'}

In [107]:
s.symmetric_difference(t) # 합집합 - 교집합.

{'dd', 'du', 'ud', 'uu'}

In [111]:
from random import randint
l = [randint(0,10) for i in range(1000)] # 0 이상 10 이하의 정수인 난수 1000개 발생
len(l)

1000

In [112]:
l[:20]

[7, 8, 8, 2, 1, 9, 9, 6, 1, 4, 7, 0, 9, 8, 2, 9, 0, 10, 7, 5]

In [113]:
s = set(l)
s

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

### list를 사용한 array

In [116]:
v = [0.5, 0.75, 1., 1.5, 2.]
m = [v,v,v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [117]:
m[1]

[0.5, 0.75, 1.0, 1.5, 2.0]

In [118]:
m[1][0]

0.5

In [119]:
v1 = [0.5, 1.5]
v2 = [1, 2]
m = [v1, v2]
c = [m, m]
c

[[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]

In [123]:
c[1][1][0]

1

In [129]:
v = [0.5, 0.75, 1., 1.5, 2.]
m = [v, v, v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [130]:
v[0] = "Python"
m # m이 바뀐다.

[['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0]]

In [131]:
from copy import deepcopy
v = [0.5, 0.75, 1., 1.5, 2.]
m = 3 * [deepcopy(v),]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [133]:
v[0] = "Python"
m # m이 바뀌지 않는다.

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

### numpy.ndarray는 n차원 배열을 쉽고 효율적으로, 그리고 고성능으로 다루기 위해 만들어졌다.

In [134]:
import numpy as np
a = np.array([0, 0.5, 1., 1.5, 2.])
type(a)

numpy.ndarray

In [135]:
a[:2]

array([0. , 0.5])

In [136]:
a.sum()

5.0

In [137]:
a.std()

0.7071067811865476

In [138]:
a.cumsum()

array([0. , 0.5, 1.5, 3. , 5. ])

In [139]:
a * 2

array([0., 1., 2., 3., 4.])

In [140]:
a ** 2

array([0.  , 0.25, 1.  , 2.25, 4.  ])

In [141]:
np.sqrt(a)

array([0.        , 0.70710678, 1.        , 1.22474487, 1.41421356])

In [143]:
b = np.array([a, a*2])
b

array([[0. , 0.5, 1. , 1.5, 2. ],
       [0. , 1. , 2. , 3. , 4. ]])

In [147]:
b[0]

array([0. , 0.5, 1. , 1.5, 2. ])

In [148]:
b[0,2]

1.0

In [149]:
b.sum()

15.0

In [150]:
b.sum(axis=0)

array([0. , 1.5, 3. , 4.5, 6. ])

In [151]:
b.sum(axis=1)

array([ 5., 10.])

In [156]:
c1 = np.zeros((2,3,4), dtype='i', order='C')
c1

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

In [157]:
c2 = np.zeros((2,3,4), order='C')
c2

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

### 구조화 배열

In [159]:
dt = np.dtype([('Name', 'S10'), ('Age', 'i4'), ('Height', 'f'), ('Children/Pets', 'i4', 2)])
s = np.array([('Smith', 45, 1.83, (0,1)),
             ('Jones', 53, 1.72, (2,2))], dtype = dt)
s

array([(b'Smith', 45, 1.83, [0, 1]), (b'Jones', 53, 1.72, [2, 2])],
      dtype=[('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [160]:
s['Name']

array([b'Smith', b'Jones'], dtype='|S10')

In [161]:
s['Height'].mean()

1.7750001

In [163]:
s[1]['Age']

53

In [167]:
r = np.random.randn(4,3)
s = np.random.randn(4,3)
r + s

array([[ 0.22887423,  1.24630703,  2.11685922],
       [-0.30422107, -0.9442262 ,  1.10772202],
       [ 2.78891375,  0.59981125,  2.07315467],
       [ 0.44839215, -0.35968717, -0.50778895]])

In [168]:
2 * r + 3

array([[4.49351106, 2.65800065, 6.24953679],
       [1.97313821, 4.8695236 , 5.10164753],
       [4.45930782, 3.59430502, 4.28658157],
       [4.36347993, 3.83960807, 2.52873025]])

In [170]:
s = np.random.randn(3)
s

array([1.14115262, 0.39806049, 0.4650096 ])

In [172]:
r + s # 브로드캐스팅

array([[1.88790815, 0.22706082, 2.089778  ],
       [0.62772173, 1.33282229, 1.51583337],
       [1.87080653, 0.695213  , 1.10830039],
       [1.82289258, 0.81786453, 0.22937473]])

In [173]:
s = np.random.randn(4)
r + s

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [174]:
r.T + s

array([[-0.83797208,  0.13096904,  0.24390938,  0.49848172],
       [-1.75572729,  1.57916173, -0.18859202,  0.23654579],
       [ 0.04004078,  1.69522369,  0.15754625, -0.41889312]])

In [175]:
r.transpose() + s

array([[-0.83797208,  0.13096904,  0.24390938,  0.49848172],
       [-1.75572729,  1.57916173, -0.18859202,  0.23654579],
       [ 0.04004078,  1.69522369,  0.15754625, -0.41889312]])

In [176]:
def f(x):
    return 3 * x + 5

In [177]:
f(0.5)

6.5

In [178]:
f(r)

array([[7.24026659, 4.48700097, 9.87430518],
       [3.45970732, 7.8042854 , 8.15247129],
       [7.18896172, 5.89145752, 6.92987236],
       [7.04521989, 6.2594121 , 4.29309537]])

In [179]:
import math
math.sin(r)

TypeError: only size-1 arrays can be converted to Python scalars

In [180]:
np.sin(r) # array as an input

array([[ 0.67926123, -0.17016753,  0.99854386],
       [-0.49116866,  0.80445761,  0.86783281],
       [ 0.6666117 ,  0.2927987 ,  0.59983173],
       [ 0.63014502,  0.40758151, -0.23346037]])

In [181]:
np.sin(np.pi)

1.2246467991473532e-16

In [182]:
x = np.random.randn(5,10000000)
y = 2 * x + 3
C = np.array((x, y), order = 'C')
F = np.array((x, y), order = 'F')
x = 0.; y = 0.
C[:2].round(2)

array([[[ 1.18, -0.96,  1.02, ...,  0.9 ,  0.61, -0.32],
        [-2.47,  1.2 , -1.87, ...,  0.1 ,  0.96, -1.63],
        [-0.01,  0.79,  0.41, ..., -1.53,  0.01, -0.4 ],
        [ 0.47,  0.61,  0.7 , ..., -2.48, -0.79, -0.19],
        [-0.39, -0.45, -0.75, ..., -0.54, -0.5 ,  1.16]],

       [[ 5.35,  1.07,  5.05, ...,  4.8 ,  4.21,  2.35],
        [-1.95,  5.39, -0.73, ...,  3.2 ,  4.92, -0.26],
        [ 2.99,  4.58,  3.81, ..., -0.06,  3.02,  2.2 ],
        [ 3.93,  4.22,  4.4 , ..., -1.96,  1.42,  2.61],
        [ 2.23,  2.09,  1.49, ...,  1.92,  2.01,  5.31]]])

In [183]:
C.shape

(2, 5, 10000000)

In [185]:
F.round(2)

array([[[ 1.18, -0.96,  1.02, ...,  0.9 ,  0.61, -0.32],
        [-2.47,  1.2 , -1.87, ...,  0.1 ,  0.96, -1.63],
        [-0.01,  0.79,  0.41, ..., -1.53,  0.01, -0.4 ],
        [ 0.47,  0.61,  0.7 , ..., -2.48, -0.79, -0.19],
        [-0.39, -0.45, -0.75, ..., -0.54, -0.5 ,  1.16]],

       [[ 5.35,  1.07,  5.05, ...,  4.8 ,  4.21,  2.35],
        [-1.95,  5.39, -0.73, ...,  3.2 ,  4.92, -0.26],
        [ 2.99,  4.58,  3.81, ..., -0.06,  3.02,  2.2 ],
        [ 3.93,  4.22,  4.4 , ..., -1.96,  1.42,  2.61],
        [ 2.23,  2.09,  1.49, ...,  1.92,  2.01,  5.31]]])